services:
  gitea:
    image: docker.gitea.com/gitea:latest
    container_name: gitea
    env_file:
      - .env
    environment:
      - USER_UID=1000
      - USER_GID=1000
      # - GITEA__database__USER=${MYSQL_USER}
      # - GITEA__database__PASSWD=${MYSQL_PASSWORD}
      # - GITEA__database__NAME=${MYSQL_DATABASE}
    #   - GITEA__database__DB_TYPE=mysql
    #   - GITEA__database__HOST=db:3306
    restart: always
    depends_on:
      - gitea_db
    networks:
      - caddy-network
      - gitea-backend
    volumes:
      - gitea:/data
      - ./themes:/data/themes
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      # - "3000:3000"
      - "22:22"


  gitea_db:
    container_name: gitea_db
    image: docker.io/library/mysql:latest
    networks:
      - gitea-backend
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - mysql:/var/lib/mysql

networks:
  gitea-backend:

volumes:
  gitea:
  mysql: