services:
  keycloak_db:
    image: mariadb:${MARIADB_VERSION:-latest}
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-toor}
      MARIADB_DATABASE: keycloak
      MARIADB_USER: keycloak
      MARIADB_PASSWORD: ${MARIADB_KEYCLOAK_PASSWORD:-keycloak}
    mem_limit: 300m
    container_name: keycloak_db
    volumes:
      - keycloak_db_data:/var/lib/mysql
    restart: always
    networks:
      - keycloak-backend
  # mail:
  #   image: bytemark/smtp:latest
  #   container_name: mail
  #   mem_limit: 50m
  #   restart: always
  #   networks:
  #     - keycloak-backend
  keycloak:
    # ports:
    #   - 8080:8080
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    environment:
      KC_DB: mariadb
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${MARIADB_KEYCLOAK_PASSWORD:-keycloak}
      KC_DB_URL_HOST: keycloak_db
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_URL: http://${KEYCLOAK_DOMAIN}
      # KC_HTTPS_CERTIFICATE_FILE: "/certs/genesis-servers.com+1.pem"
      # KC_HTTPS_CERTIFICATE_KEY_FILE: "/certs/genesis-servers.com+1-key.pem"
    mem_limit: 500m
    command: start
    container_name: keycloak
    volumes:
      - ./themes:/opt/keycloak/themes
    restart: always
    networks:
      - keycloak-backend
      - caddy-network
    depends_on:
      - keycloak_db
      # - mail
  # nginx:
  #   image: nginx:${NGINX_VERSION:-latest}
  #   environment:
  #     KEYCLOAK_DOMAIN: ${KEYCLOAK_DOMAIN}
  #   mem_limit: 100m
  #   container_name: nginx
  #   volumes:
  #     - ./nginx/templates:/etc/nginx/templates
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   ports:
  #     - 80:80
  #     - 443:443
  #   restart: always
  #   networks:
  #     - keycloak-backend
  # certbot:
  #   image: certbot/certbot:${CERTBOT_VERSION:-latest}
  #   environment:
  #     CERTBOT_LETSENCRYPT_EMAIL: ${CERTBOT_LETSENCRYPT_EMAIL}
  #     KEYCLOAK_DOMAIN: ${KEYCLOAK_DOMAIN}
  #   mem_limit: 50m
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: certonly --non-interactive --webroot -w /var/www/certbot --email ${CERTBOT_LETSENCRYPT_EMAIL} -d ${KEYCLOAK_DOMAIN} --agree-tos
  #   depends_on:
  #     - nginx

volumes:
  keycloak_db_data:
    driver: local

networks:
  keycloak-backend:
  # caddy-network:
  #   external: true